### ISSUE TITLE
Logstash crashes when xmpp host is unavailable.

### ISSUE THREAD

**Issue by ghost** [logstash-plugins/logstash-output-xmpp#7]
- Version: Logstash v5.6.4 + plugin v3.0.6, Logstash v6.2.1 + plugin v3.0.7
- Operating System: Centos 7.4
- Config File 
```
output{
  if "icinga" in [tags]{

      if "alerts" in [tags]{


        xmpp {
            message => "%{state}: %{host_name} - %{errormessage}"
            host    => "int-jabber-01"
            user    => "xmpp-service@company.org"
            password=> "some_password"
            rooms   => "icinga@conference.company.org/Office"
      }
    }
  }
}
```
- Sample Data: Any
- Steps to Reproduce: Enable xmpp output, make xmpp server unaccessible, wait or restart logstash.

Logs
```
root@dev-alex-02:~  # /usr/share/logstash/bin/logstash -f /etc/logstash/conf.d/
WARNING: Could not find logstash.yml which is typically located in $LS_HOME/config or /etc/logstash. You can specify the path using --path.settings. Continuing using the defaults
Could not find log4j2 configuration at path /usr/share/logstash/config/log4j2.properties. Using default config which logs errors to the console
[INFO ] 2018-02-19 09:51:44.254 [main] scaffold - Initializing module {:module_name=>"netflow", :directory=>"/usr/share/logstash/modules/netflow/configuration"}
[INFO ] 2018-02-19 09:51:44.265 [main] scaffold - Initializing module {:module_name=>"fb_apache", :directory=>"/usr/share/logstash/modules/fb_apache/configuration"}
[WARN ] 2018-02-19 09:51:44.951 [LogStash::Runner] multilocal - Ignoring the 'pipelines.yml' file because modules or command line options are specified
[INFO ] 2018-02-19 09:51:45.202 [LogStash::Runner] runner - Starting Logstash {"logstash.version"=>"6.2.1"}
[INFO ] 2018-02-19 09:51:45.303 [Api Webserver] agent - Successfully started Logstash API endpoint {:port=>9600}
[INFO ] 2018-02-19 09:51:49.357 [Ruby-0-Thread-1: /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:22] pipeline - Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>4, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50}
[INFO ] 2018-02-19 09:51:49.886 [[main]-pipeline-manager] elasticsearch - Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://int-elastic-04:9200/, http://int-elastic-05:9200/, http://int-elastic-06:9200/]}}
[INFO ] 2018-02-19 09:51:49.891 [[main]-pipeline-manager] elasticsearch - Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://int-elastic-04:9200/, :path=>"/"}
[WARN ] 2018-02-19 09:51:50.070 [[main]-pipeline-manager] elasticsearch - Restored connection to ES instance {:url=>"http://int-elastic-04:9200/"}
[INFO ] 2018-02-19 09:51:50.331 [[main]-pipeline-manager] elasticsearch - ES Output version determined {:es_version=>nil}
[INFO ] 2018-02-19 09:51:50.331 [[main]-pipeline-manager] elasticsearch - Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://int-elastic-05:9200/, :path=>"/"}
[WARN ] 2018-02-19 09:51:50.339 [[main]-pipeline-manager] elasticsearch - Restored connection to ES instance {:url=>"http://int-elastic-05:9200/"}
[INFO ] 2018-02-19 09:51:50.343 [[main]-pipeline-manager] elasticsearch - Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://int-elastic-06:9200/, :path=>"/"}
[WARN ] 2018-02-19 09:51:50.349 [[main]-pipeline-manager] elasticsearch - Restored connection to ES instance {:url=>"http://int-elastic-06:9200/"}
[INFO ] 2018-02-19 09:51:50.354 [[main]-pipeline-manager] elasticsearch - Using mapping template from {:path=>nil}
[INFO ] 2018-02-19 09:51:50.358 [[main]-pipeline-manager] elasticsearch - Attempting to install template {:manage_template=>{"template"=>"logstash-*", "version"=>50001, "settings"=>{"index.refresh_interval"=>"5s"}, "mappings"=>{"_default_"=>{"_all"=>{"enabled"=>true, "norms"=>false}, "dynamic_templates"=>[{"message_field"=>{"path_match"=>"message", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false}}}, {"string_fields"=>{"match"=>"*", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false, "fields"=>{"keyword"=>{"type"=>"keyword", "ignore_above"=>256}}}}}], "properties"=>{"@timestamp"=>{"type"=>"date", "include_in_all"=>false}, "@version"=>{"type"=>"keyword", "include_in_all"=>false}, "geoip"=>{"dynamic"=>true, "properties"=>{"ip"=>{"type"=>"ip"}, "location"=>{"type"=>"geo_point"}, "latitude"=>{"type"=>"half_float"}, "longitude"=>{"type"=>"half_float"}}}}}}}}
[INFO ] 2018-02-19 09:51:50.367 [[main]-pipeline-manager] elasticsearch - New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["//int-elastic-04", "//int-elastic-05", "//int-elastic-06"]}
D, [2018-02-19T09:51:50.811672 #31033] DEBUG -- : Debugging mode enabled.
W, [2018-02-19T09:51:50.830276 #31033]  WARN -- : Warnings mode enabled.
D, [2018-02-19T09:51:50.837866 #31033] DEBUG -- : CONNECTING:
    int-jabber-01:5222
[ERROR] 2018-02-19 09:51:51.908 [[main]-pipeline-manager] pipeline - Error registering plugin {:pipeline_id=>"main", :plugin=>"#<LogStash::OutputDelegator:0x40b5ad35 @namespaced_metric=#<LogStash::Instrument::NamespacedMetric:0x7c176888 @metric=#<LogStash::Instrument::Metric:0x3e7f1306 @collector=#<LogStash::Instrument::Collector:0x1ad0b741 @agent=nil, @metric_store=#<LogStash::Instrument::MetricStore:0x77e16d2b @store=#<Concurrent::Map:0x00000000000fb0 entries=4 default_proc=nil>, @structured_lookup_mutex=#<Mutex:0x30750877>, @fast_lookup=#<Concurrent::Map:0x00000000000fb4 entries=163 default_proc=nil>>>>, @namespace_name=[:stats, :pipelines, :main, :plugins, :outputs, :\"7bce857858f1ae067b288284d602f3a32ca5e154e55f29214d7ca92f66eb55a8\"]>, @metric=#<LogStash::Instrument::NamespacedMetric:0x69211178 @metric=#<LogStash::Instrument::Metric:0x3e7f1306 @collector=#<LogStash::Instrument::Collector:0x1ad0b741 @agent=nil, @metric_store=#<LogStash::Instrument::MetricStore:0x77e16d2b @store=#<Concurrent::Map:0x00000000000fb0 entries=4 default_proc=nil>, @structured_lookup_mutex=#<Mutex:0x30750877>, @fast_lookup=#<Concurrent::Map:0x00000000000fb4 entries=163 default_proc=nil>>>>, @namespace_name=[:stats, :pipelines, :main, :plugins, :outputs]>, @out_counter=org.jruby.proxy.org.logstash.instrument.metrics.counter.LongCounter$Proxy2 -  name: out value:0, @strategy=#<LogStash::OutputDelegatorStrategies::Legacy:0xdfb352f @worker_count=1, @workers=[<LogStash::Outputs::Xmpp message=>\"%{short_app_url}:%{tag} is deploying on %{logsource}\", host=>\"int-jabber-01\", user=>\"xmpp-service@infoxchange.org\", password=><password>, rooms=>[\"logstash@conference.infoxchange.org/Logstash_int\"], id=>\"7bce857858f1ae067b288284d602f3a32ca5e154e55f29214d7ca92f66eb55a8\", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>\"plain_26f33f24-2ed5-4b90-b8b7-95da817c4253\", enable_metric=>true, charset=>\"UTF-8\">, workers=>1>], @worker_queue=#<SizedQueue:0x3ce6f8fa>>, @in_counter=org.jruby.proxy.org.logstash.instrument.metrics.counter.LongCounter$Proxy2 -  name: in value:0, @id=\"7bce857858f1ae067b288284d602f3a32ca5e154e55f29214d7ca92f66eb55a8\", @time_metric=org.jruby.proxy.org.logstash.instrument.metrics.counter.LongCounter$Proxy2 -  name: duration_in_millis value:0, @metric_events=#<LogStash::Instrument::NamespacedMetric:0x4819185 @metric=#<LogStash::Instrument::Metric:0x3e7f1306 @collector=#<LogStash::Instrument::Collector:0x1ad0b741 @agent=nil, @metric_store=#<LogStash::Instrument::MetricStore:0x77e16d2b @store=#<Concurrent::Map:0x00000000000fb0 entries=4 default_proc=nil>, @structured_lookup_mutex=#<Mutex:0x30750877>, @fast_lookup=#<Concurrent::Map:0x00000000000fb4 entries=163 default_proc=nil>>>>, @namespace_name=[:stats, :pipelines, :main, :plugins, :outputs, :\"7bce857858f1ae067b288284d602f3a32ca5e154e55f29214d7ca92f66eb55a8\", :events]>, @output_class=LogStash::Outputs::Xmpp>", :error=>"Connection refused - connect(2) for \"int-jabber-01\" port 5222", :thread=>"#<Thread:0x615cd639@/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:246 run>"}
[ERROR] 2018-02-19 09:51:52.362 [[main]-pipeline-manager] pipeline - Pipeline aborted due to error {:pipeline_id=>"main", :exception=>#<Errno::ECONNREFUSED: Connection refused - connect(2) for "int-jabber-01" port 5222>, :backtrace=>["org/jruby/ext/socket/RubyTCPSocket.java:134:in `initialize'", "org/jruby/RubyIO.java:875:in `new'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/xmpp4r-0.5.6/lib/xmpp4r/connection.rb:76:in `connect'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/xmpp4r-0.5.6/lib/xmpp4r/client.rb:71:in `connect'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-xmpp-3.0.7/lib/logstash/outputs/xmpp.rb:55:in `connect'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-output-xmpp-3.0.7/lib/logstash/outputs/xmpp.rb:35:in `register'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator_strategies/legacy.rb:17:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator.rb:42:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:341:in `register_plugin'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:352:in `block in register_plugins'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:352:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:735:in `maybe_setup_out_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:362:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:289:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:249:in `block in start'"], :thread=>"#<Thread:0x615cd639@/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:246 run>"}
[ERROR] 2018-02-19 09:51:52.386 [Ruby-0-Thread-1: /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:22] agent - Failed to execute action {:id=>:main, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Could not execute action: LogStash::PipelineAction::Create/pipeline_id:main, action_result: false", :backtrace=>nil}
```

**Comment by sammcj** [comment]
This is a blocking issue for us as we can't have all (logstash) logging go offline just because the XMPP/Jabber chat service is down. I would have expected errors in the logstash logs stating the service is unavailable, but not hard crashing.

**Comment by sammcj** [comment]
Sorry to be a nag - but is anyone able to look into this? It's quite a serious problem.

**Comment by jsvd** [comment]
I haven't been able to see an exception like the one posted in this issue, but from my tests I confirm that if jabber goes down after connecting logstash will terminate. In my tests, I saw the following:

```
[2018-03-09T17:32:27,528][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<NoMethodError: undefined method `node' for nil:NilClass>, :backtrace=>["/tmp/logstash-6.2.1/vendor/bundle/jruby/2.3.0/gems/xmpp4r-0.5.6/lib/xmpp4r/muc/helper/mucclient.rb:260:in `send'", "/tmp/logstash-6.2.1/vendor/bundle/jruby/2.3.0/gems/logstash-output-xmpp-3.0.7/lib/logstash/outputs/xmpp.rb:74:in `block in receive'"
```

This is simple due to the fact that the plugin code is extremely simple and fragile.
There needs to be an error control flow that retries to connect if an error happens while sending a message.

Any takers to implement this? I'd be more than glad to review it.

**Comment by sammcj** [comment]
Thanks @jsvd, I've submitted a simple MR that prevents Logstash from crashing if the XMPP/Jabber server becomes unavailable _after_ Logstash has started: https://github.com/logstash-plugins/logstash-output-xmpp/pull/8

However this plugin does need a rewrite or at least some error handling added in order to resolve this bug.
